# Generated by Django 4.0.5 on 2022-07-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_tutorial_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='url',
        ),
    ]
