# Generated by Django 4.0.5 on 2022-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_tutorial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='content',
            field=models.TextField(default='full content of the article'),
        ),
    ]
